version: "3"

services:
    nginx:
        container_name: nginx
        build: requirements/nginx
        image: nginx
        volumes:
            - WordPress:/var/www/html/wordpress
        ports:
            - "443:443"
        depends_on:
            - "wordpress"    
        restart: always
        networks:
            - inception_network
    wordpress:
        env_file:
            - .env
        container_name: wordpress
        build:
            context: requirements/wordpress
            args:
                - PASSWORDDB={PASSWORDDB}
        image: wordpress
        volumes:
            - WordPress:/var/www/html/wordpress
        #ports:
        #    - "9000:9000"
        restart: always
        networks:
            - inception_network
        depends_on:
            - "mariadb"    
    mariadb:
        env_file:
            - .env
        container_name: mariadb
        build:
            context: requirements/mariadb
            args:
                - PASSWORDDB={PASSWORDDB}
                - PASSWORDROOT={PASSWORDROOT}
        image: mariadb
        volumes:
           - DB:/var/lib/mysql/
        #ports:
        #    - "3306:3306"
        restart: always
        networks:
            - inception_network    

networks:
  inception_network:
    driver: bridge

volumes:
    WordPress:
        driver: local
        driver_opts: 
            type:
                none
            device: /home/nschmitt/data/WordPress
            o: bind
    DB:
        driver: local
        driver_opts: 
            type:
                none
            device: /home/nschmitt/data/DB
            o: bind
